### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HipsterBrown** [namely/styleguide#93]
This will be an open issue of tasks needed to be done for a stable release of the styleguide. Please contribute with anything you feel may be missing from the list, as well as volunteering to lead the charge on any of the tasks. A task should link to a corresponding issue. 

## TODO
- [ ] #87 Refactor documentation generation workflow, a.k.a new static site
- [ ] #85 Fix broken edit-label component
- [ ] #61 Display Border Types in Styleguide
- [ ] #43 Icon vertical alignment (?)
- [ ] #77 Fix table sorting styles
- [ ] #89 Document "states" utilities
- [ ] #90 Document "animation" utilities
- [ ] #91 Document "layout" utilities 
- [ ] #92 Document rest of "element" styles
- [ ] (needs issue) Document FileUpload component
- [ ] (needs issue) Document EditLabel component
- [ ] (needs issue) Document Popup component
- [ ] (needs issue) Document OutsideClick mixin
- [ ] (needs issue) Document new/update component workflow
- [ ] (needs issue) Document new/update css utility workflow
- [ ] (needs issue) Add scss-lint check for CircleCI builds
- [ ] (needs issue) Add component linter for CircleCI builds
